# Generated by Django 5.0.6 on 2024-07-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_mcq_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='quiz_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poll',
            name='quiz_visible',
            field=models.BooleanField(default=False),
        ),
    ]
